[package]
name = "keiga"
version = "1.4.1"
edition = "2024"
description = "Lightweight image optimizer"
authors = ["yoshitaka-k"]
repository = "yoshitaka-k/keiga"
license = "Apache-2.0"

[profile.release]
# サイズ小さくしてパフォーマンスアップ狙う
lto = true
# 並列コード生成をやめる
codegen-units = 1
# デバッグシンボル・シンボルテーブルを削る
strip = true

[package.metadata.bundle]
identifier = "jp.ktgwya.keiga"
name = "Keiga"
icon = ["target/bundle-icons/*.png"]
category = "Utility"
short_description = "Lightweight image optimizer"
linux_use_terminal = false
deb_depends = [
    "libgtk-3-0",
    "libxcb-render0",
    "libxcb-shape0",
    "libxcb-xfixes0",
    "libxkbcommon0",
    "libvulkan1",
    "libssl3",
]

[package.metadata.winresource]
ProductName = "Keiga"
FileDescription = "Lightweight image optimizer"
OriginalFilename = "Keiga.exe"

[build-dependencies]
serde = { version = "1.0.229", features = ["derive"] }
image = { version = "0.25.10", default-features = false, features = ["png"] }
winresource = "0.1.31"
ico = "0.5"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["winbase"] }

[dependencies]
egui = "0.36.1"
egui_extras = { version = "0.36.1", features = ["svg", "image"] }
eframe = { version = "0.36.1", features = ["persistence"] }
rfd = "0.17.2"
serde = { version = "1.0.229", features = ["derive"] }
image = { version = "0.25.10", default-features = false, features = ["jpeg", "png"] }
oxipng = { version = "10.2.0", default-features = false, features = ["parallel"] }
rayon = "1.12.0"
getset = "0.1.7"
env_logger = "0.11.11"
log = "0.4.33"
ehttp = { version = "0.7.1", features = ["json"] }
serde_json = "1.0.151"
rodio = "0.22.2"
